In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Create Numpy Array With Numpy Function

In [ ]:
# Array filled with 0`s
# Array filled with 1`s
# Create an empty array
# An array with a range of element 
# Array diagonal element filled with 1`s
# Create an array with values that are spaced linearly in a specified interval

# Zeros
Array made with zeros

In [ ]:
# making array with zero 

import numpy as np

In [ ]:
ar_zero = np.zeros(4)
print(ar_zero) # here the array make with zeros one D array

In [ ]:
# making two diamension array with zero 2 D array 

ar_zero = np.zeros((3,4))
print(ar_zero)

# Ones
Array made with ones

In [ ]:
# we made another array with one 

ar_one = np.ones(5)
print(ar_one) # the out put is one D array

In [ ]:
ar_one = np.ones((3,3))
print(type(ar_one))
print(ar_one)

print(ar_one.ndim)   # this is a 2 D array this function is use to check the Dimen---

# Empty 
Array made with empty function

In [ ]:
# we made an other array that is empty array 
#  we made empty array 

ar_em = np.empty(4)
print(ar_em)

# Range
Array made with range function

In [ ]:
# we made an other array with the help of range function 

ar_rn = np.arange(4) # range perform the operation from zero to n-1 
print(ar_rn)
print(type(ar_rn))

# Diagonal 
Array made with diagonal element

"only diagonal element will be 1 and othe will be 0"

for diagonal function we use ""eye"" function

In [ ]:
ar_dia = np.eye(3)
print(ar_dia) # array made with diagonal element and use the "eye" function

In [ ]:
import numpy as np
ar_dia = np.eye(3,3)
print(ar_dia)

# line space 

in that function we use "linespace" function that create a gap in the array

In [ ]:
# we use a specific function thats put a gap in te array function

ar_line = np.linspace(0,20,num=5)
print(ar_line)

# Reshaped 

reshape use to re design the 1 D array in multi D array

In [22]:
# made 1 D array 
import numpy as np
ar_1d = np.arange(1,13)
print(ar_1d) 
print(ar_1d.ndim) # this is one diamensional array and now converted in two multi diamensional

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

In [16]:
# we use the reshaped functionn 
# 1 D array converted in to 2 D 

ar_2d = ar_1d.reshape(2,4)
print(ar_2d) # this converts in two two diamensional array

[[1 2 3 4]
 [5 6 7 8]]

In [23]:
#  1D array converted in to 3D

ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

In [24]:
# a single line array function converted in to 2 D

ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

# Ravel 

Ravel function convert 2D Array in to 1D

In [25]:
ar.ravel() # if i use the .ravel function then the 2D array convert in to 1 D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Flatten

flaten function convert multi diamensional array in to 1 D

In [27]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose

transpose function is use to convert row in to coloum

In [28]:
ar.transpose()

# the transpose matrix which is 2 by 6 convert in to 6 by 2

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [30]:
# transpose function ki jangha hum ar.T ka bhi use kar sakte hai 
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])